language: php

php:
  - 5.5
  - 5.4

before_install:
    - composer self-update
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - mysql -e 'CREATE DATABASE p2s_test'
    - mysql -e 'CREATE USER p2s_test@localhost IDENTIFIED BY `p2s_test`'
    - mysql -e 'GRANT USAGE ON p2s_test.* to p2s_test@localhost IDENTIFIED BY `p2s_test`'
    - mysql -e 'GRANT ALL PRIVILEGES ON p2s_test.* to p2s_test@localhost'

before_script:
    - composer install
    - app/console doctrine:migrations:migrate --no-interaction --env=test

script:
    - phpunit -c app --exclude-group=functional
    - phpunit -c app --group=functional
