parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_name: p2s
    database_user: p2s
    database_password: p2s

    mailer_transport: gmail
    mailer_user: "test@test.com"
    mailer_password: ""

    locale: en

    secret: thisisasecret
